-- Timesheet App schema.
--
-- This script is additive and safe to run repeatedly against a database
-- that already has data: every statement is idempotent (IF NOT EXISTS,
-- CREATE OR REPLACE, or an existence check before ALTER), and nothing
-- drops or truncates a table. Rerunning it only fills in whatever is
-- missing.
--
-- Standing rules enforced here (see CLAUDE.md for the full list):
--   1. timesheets has no status column. Status is derived as the type of
--      the latest event for that timesheet.
--   2. The events table is append-only: a trigger raises on UPDATE and on
--      DELETE of any row in events.
--   3. Money and limits are snapshotted onto events (payload jsonb), never
--      recomputed later.
--   4. rates are effective-dated rows; a rate change is an INSERT. A
--      correction is a new row sharing the same effective_from as the row
--      it corrects — recorded_at breaks the tie (latest wins).
--   5. The pay calendar is derived by rule (lib/paycalendar.ts), not stored.
--   6. rates, admin_log and contract_terms are append-only too (same
--      trigger pattern as events). Every rate carries a required contract
--      reference. contract_terms holds end dates the same way: never
--      edited, only superseded.
--
-- All identity columns are GENERATED BY DEFAULT (not ALWAYS): the seed
-- builder assigns deterministic ids for every row up front so it never has
-- to infer id-to-row linkage from RETURNING order, and ordinary app inserts
-- still get an auto-generated id when they omit one.

begin;

create table if not exists entities (
  id          bigint generated by default as identity primary key,
  name        text not null unique,
  domain      text not null unique
);

create table if not exists users (
  id          bigint generated by default as identity primary key,
  name        text not null,
  entity_id   bigint not null references entities (id),
  role        text not null check (role in ('intern', 'consultant', 'manager', 'admin')),
  pay_type    text not null check (pay_type in ('hourly', 'salaried')),
  function    text not null check (function in (
                'Delivery', 'Solutions & Support', 'Product Engineering',
                'R&D', 'Sales & Marketing', 'G&A'
              )),
  manager_id  bigint references users (id),
  weekly_cap  numeric(5, 2) not null default 40,
  daily_cap   numeric(4, 2) not null default 8,
  active      boolean not null default true
);

create index if not exists users_entity_id_idx on users (entity_id);
create index if not exists users_manager_id_idx on users (manager_id);

create table if not exists rates (
  id              bigint generated by default as identity primary key,
  user_id         bigint not null references users (id),
  hourly          numeric(8, 2) not null check (hourly > 0),
  effective_from  date not null
);

create index if not exists rates_user_id_effective_from_idx on rates (user_id, effective_from);

-- A rate typo is corrected by inserting a new row with the SAME
-- effective_from as the one it corrects (never by editing or deleting
-- it), so effective_from can no longer be unique per user. recorded_at
-- breaks the tie: rateAsOf reads the latest effective_from <= a date,
-- and among rows sharing that effective_from, the latest recorded_at.
alter table rates drop constraint if exists rates_user_id_effective_from_key;
alter table rates add column if not exists recorded_at timestamptz not null default now();
create index if not exists rates_user_id_recorded_at_idx on rates (user_id, recorded_at);

-- Contract reference behind every rate (D8) — added nullable, backfilled
-- for any pre-existing rows (a real reseed replaces these anyway), then
-- made required, so this migration stays safe to rerun against a
-- database that already has rate rows from before this rule existed.
alter table rates add column if not exists contract_ref text;
alter table rates add column if not exists contract_signed_on date;
update rates set contract_ref = 'CTR-LEGACY-' || id where contract_ref is null;
update rates set contract_signed_on = effective_from where contract_signed_on is null;
alter table rates alter column contract_ref set not null;
alter table rates alter column contract_signed_on set not null;

-- Who recorded this row — null for the original seed data (installed by
-- no accountable admin), set for every row an admin adds through the app.
alter table rates add column if not exists recorded_by bigint references users (id);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'rates_contract_ref_not_blank'
  ) then
    alter table rates add constraint rates_contract_ref_not_blank check (btrim(contract_ref) <> '');
  end if;
end
$$;

create table if not exists customers (
  id          bigint generated by default as identity primary key,
  entity_id   bigint not null references entities (id),
  name        text not null,
  status      text not null check (status in ('Active', 'Churned')),
  unique (entity_id, name)
);

create index if not exists customers_entity_id_idx on customers (entity_id);

create table if not exists streams (
  id              bigint generated by default as identity primary key,
  entity_id       bigint not null references entities (id),
  name            text not null,
  billable        boolean not null,
  customer_rule   text not null check (customer_rule in ('required', 'optional', 'none')),
  default_account text,
  unique (entity_id, name)
);

create index if not exists streams_entity_id_idx on streams (entity_id);

create table if not exists accounts (
  code  text primary key,
  name  text not null
);

-- streams.default_account references accounts, but accounts is created
-- after streams above for FK ordering; add the constraint if it isn't
-- there yet (ALTER TABLE ADD CONSTRAINT has no IF NOT EXISTS form).
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'streams_default_account_fkey'
  ) then
    alter table streams
      add constraint streams_default_account_fkey
      foreign key (default_account) references accounts (code);
  end if;
end
$$;

create table if not exists holidays (
  date  date primary key,
  name  text not null
);

create table if not exists time_off (
  id      bigint generated by default as identity primary key,
  user_id bigint not null references users (id),
  date    date not null,
  label   text not null,
  unique (user_id, date)
);

create index if not exists time_off_user_id_idx on time_off (user_id);

create table if not exists timesheets (
  id          bigint generated by default as identity primary key,
  user_id     bigint not null references users (id),
  entity_id   bigint not null references entities (id),
  week_ending date not null,
  stream_id   bigint not null references streams (id),
  customer_id bigint references customers (id),
  notes       text,
  unique (user_id, week_ending)
);

create index if not exists timesheets_user_id_idx on timesheets (user_id);
create index if not exists timesheets_entity_id_idx on timesheets (entity_id);
create index if not exists timesheets_week_ending_idx on timesheets (week_ending);

-- The Mon-Fri hours while a sheet is in draft (status computed from
-- events — see lib/status.ts). Once submitted, the submitted event's
-- payload is the record of what was sent; draft_hours is only ever read
-- or written while the timesheet is still in draft (enforced in the
-- server action, not here — see CLAUDE.md "every rule is enforced on the
-- server"). Shape mirrors the submitted payload's hours: {mon,tue,wed,thu,fri}.
alter table timesheets add column if not exists draft_hours jsonb;

create table if not exists events (
  id           bigint generated by default as identity primary key,
  timesheet_id bigint not null references timesheets (id),
  type         text not null check (type in (
                 'created', 'submitted', 'returned', 'approved',
                 'processed', 'reopened'
               )),
  actor_id     bigint not null references users (id),
  at           timestamptz not null default now(),
  payload      jsonb not null default '{}'::jsonb
);

create index if not exists events_timesheet_id_at_idx on events (timesheet_id, at);

-- Rule 2: events is append-only.
create or replace function events_no_update_no_delete()
returns trigger
language plpgsql
as $$
begin
  raise exception 'events is append-only: % is not allowed on events', tg_op;
end;
$$;

drop trigger if exists events_no_update on events;
create trigger events_no_update
  before update on events
  for each row execute function events_no_update_no_delete();

drop trigger if exists events_no_delete on events;
create trigger events_no_delete
  before delete on events
  for each row execute function events_no_update_no_delete();

-- Rule 12: rates, admin_log and contract_terms are append-only too, same
-- pattern as events. One generic function (parameterized by TG_TABLE_NAME
-- rather than hardcoding "events" the way events_no_update_no_delete
-- does) instead of three near-copies of it.
create or replace function no_update_no_delete()
returns trigger
language plpgsql
as $$
begin
  raise exception '% is append-only: % is not allowed on %', TG_TABLE_NAME, TG_OP, TG_TABLE_NAME;
end;
$$;

drop trigger if exists rates_no_update on rates;
create trigger rates_no_update
  before update on rates
  for each row execute function no_update_no_delete();

drop trigger if exists rates_no_delete on rates;
create trigger rates_no_delete
  before delete on rates
  for each row execute function no_update_no_delete();

create table if not exists notifications (
  id      bigint generated by default as identity primary key,
  user_id bigint not null references users (id),
  at      timestamptz not null default now(),
  read_at timestamptz,
  text    text not null,
  target  jsonb not null default '{}'::jsonb
);

create index if not exists notifications_user_id_idx on notifications (user_id);

create table if not exists chases (
  id             bigint generated by default as identity primary key,
  at             timestamptz not null default now(),
  by_user_id     bigint not null references users (id),
  target_user_id bigint not null references users (id)
);

create index if not exists chases_target_user_id_idx on chases (target_user_id);

create table if not exists admin_log (
  id        bigint generated by default as identity primary key,
  at        timestamptz not null default now(),
  actor_id  bigint not null references users (id),
  user_id   bigint not null references users (id),
  text      text not null
);

create index if not exists admin_log_user_id_idx on admin_log (user_id);

drop trigger if exists admin_log_no_update on admin_log;
create trigger admin_log_no_update
  before update on admin_log
  for each row execute function no_update_no_delete();

drop trigger if exists admin_log_no_delete on admin_log;
create trigger admin_log_no_delete
  before delete on admin_log
  for each row execute function no_update_no_delete();

-- Contract end dates (D9). The end date in force for a user is the
-- latest recorded row for them — never edited or deleted, only
-- superseded (kind documents why: an initial 'set', an 'extend', or an
-- admin 'shorten' — a manager may only ever record 'extend').
create table if not exists contract_terms (
  id                  bigint generated by default as identity primary key,
  user_id             bigint not null references users (id),
  end_date            date not null,
  contract_ref        text not null check (btrim(contract_ref) <> ''),
  contract_signed_on  date not null,
  recorded_at         timestamptz not null default now(),
  recorded_by         bigint not null references users (id),
  kind                text not null check (kind in ('set', 'extend', 'shorten'))
);

create index if not exists contract_terms_user_id_recorded_at_idx on contract_terms (user_id, recorded_at);

drop trigger if exists contract_terms_no_update on contract_terms;
create trigger contract_terms_no_update
  before update on contract_terms
  for each row execute function no_update_no_delete();

drop trigger if exists contract_terms_no_delete on contract_terms;
create trigger contract_terms_no_delete
  before delete on contract_terms
  for each row execute function no_update_no_delete();

-- Caps traced to contracts (item b). Weekly and daily caps used to be
-- in-place columns on users, with nothing saying which contract set
-- them. They are effective-by-recording the same way contract_terms is:
-- the caps IN FORCE for a person are the latest recorded row, never
-- edited, only superseded, and every row cites the contract that agreed
-- them.
create table if not exists cap_terms (
  id                  bigint generated by default as identity primary key,
  user_id             bigint not null references users (id),
  weekly_cap          numeric(5, 2) not null check (weekly_cap > 0),
  daily_cap           numeric(4, 2) not null check (daily_cap > 0),
  contract_ref        text not null check (btrim(contract_ref) <> ''),
  contract_signed_on  date not null,
  recorded_at         timestamptz not null default now(),
  recorded_by         bigint not null references users (id)
);

create index if not exists cap_terms_user_id_recorded_at_idx on cap_terms (user_id, recorded_at);

drop trigger if exists cap_terms_no_update on cap_terms;
create trigger cap_terms_no_update
  before update on cap_terms
  for each row execute function no_update_no_delete();

drop trigger if exists cap_terms_no_delete on cap_terms;
create trigger cap_terms_no_delete
  before delete on cap_terms
  for each row execute function no_update_no_delete();

-- users.weekly_cap / users.daily_cap are RETIRED by cap_terms above.
-- Nothing anywhere reads or writes them now, and the seed leaves them
-- null. They are still DEFINED here on purpose: local proofs, preview
-- deployments and production share one database, so until this branch
-- merges the code on main still runs a check that selects these two
-- columns. Removing the definitions would break that code the moment
-- anyone built a fresh database from this file. The drop
-- ("alter table users drop column if exists ...") belongs in a
-- separate pass, once no deployed code mentions them.
--
-- Relaxing NOT NULL and the default is idempotent — a no-op once
-- applied — and makes a stale leftover value impossible to mistake for
-- the caps in force.
alter table users alter column weekly_cap drop not null;
alter table users alter column daily_cap  drop not null;
alter table users alter column weekly_cap drop default;
alter table users alter column daily_cap  drop default;

-- Singleton table (the boolean PK constrained to true allows exactly one
-- row) holding the seed's anchor Friday and when the demo was last rebuilt.
-- The app checks this on every request: if the anchor is older than the
-- current most recent Friday, it reseeds before rendering.
create table if not exists demo_meta (
  id             boolean primary key default true check (id),
  anchor_friday  date not null,
  last_reset_at  timestamptz not null
);

commit;
