// Truncates and rebuilds all data from db/seedData.ts's deterministic
// builder, then runs the required verification queries and proves the
// events append-only trigger. Run with: npm run db:seed
// Reads DIRECT_URL (falling back to DATABASE_URL) from the environment.
// Never logs the connection string.
//
// `npm run db:seed -- --dry-run` builds the same data in memory and prints
// a summary WITHOUT connecting to any database (no env vars needed).
//
// Every row db/seedData.ts builds already carries its own deterministic id
// and fully-resolved integer foreign keys, so every insert below specifies
// its id explicitly (schema.sql's identity columns are GENERATED BY
// DEFAULT so that's allowed) — nothing here depends on RETURNING order.

import { Pool, type PoolClient } from "@neondatabase/serverless";
import { STATUSES, statusFromLatestEventType } from "../lib/status";
import { buildSeed, summarize, type SeedResult } from "./seedData";

async function insertBatch(
  client: PoolClient,
  table: string,
  columns: string[],
  rows: unknown[][],
  batchSize = 500,
): Promise<void> {
  for (let start = 0; start < rows.length; start += batchSize) {
    const chunk = rows.slice(start, start + batchSize);
    const values: unknown[] = [];
    const tuples: string[] = [];
    for (const row of chunk) {
      const placeholders = row.map((_, i) => `$${values.length + i + 1}`);
      tuples.push(`(${placeholders.join(", ")})`);
      values.push(...row);
    }
    const sql = `insert into ${table} (${columns.join(", ")}) values ${tuples.join(", ")}`;
    await client.query(sql, values);
  }
}

// Tables whose id is a real identity column — after seeding with explicit
// ids, the sequence needs to catch up so ordinary app inserts don't collide.
const IDENTITY_TABLES = [
  "entities", "users", "rates", "customers", "streams",
  "time_off", "timesheets", "events", "notifications", "chases", "admin_log",
];

async function seedDatabase(client: PoolClient, seed: SeedResult) {
  await client.query("begin");
  try {
    await client.query(`
      truncate table
        admin_log, chases, notifications, events, timesheets,
        time_off, holidays, streams, customers, accounts, rates, users, entities
      restart identity cascade
    `);

    await insertBatch(
      client,
      "entities",
      ["id", "name", "domain"],
      seed.entities.map((e) => [e.id, e.name, e.domain]),
    );

    await insertBatch(
      client,
      "accounts",
      ["code", "name"],
      seed.accounts.map((a) => [a.code, a.name]),
    );

    // users: insert with manager_id null first (self-referential FK),
    // then backfill — every id is already known, so this is a plain update.
    await insertBatch(
      client,
      "users",
      ["id", "name", "entity_id", "role", "pay_type", "function", "weekly_cap", "daily_cap", "active"],
      seed.users.map((u) => [u.id, u.name, u.entityId, u.role, u.payType, u.function, u.weeklyCap, u.dailyCap, u.active]),
    );
    for (const u of seed.users) {
      if (u.managerId === null) continue;
      await client.query("update users set manager_id = $1 where id = $2", [u.managerId, u.id]);
    }

    await insertBatch(
      client,
      "rates",
      ["id", "user_id", "hourly", "effective_from"],
      seed.rates.map((r) => [r.id, r.userId, r.hourly, r.effectiveFrom]),
    );

    await insertBatch(
      client,
      "customers",
      ["id", "entity_id", "name", "status"],
      seed.customers.map((c) => [c.id, c.entityId, c.name, c.status]),
    );

    await insertBatch(
      client,
      "streams",
      ["id", "entity_id", "name", "billable", "customer_rule", "default_account"],
      seed.streams.map((s) => [s.id, s.entityId, s.name, s.billable, s.customerRule, s.defaultAccount]),
    );

    await insertBatch(
      client,
      "holidays",
      ["date", "name"],
      seed.holidays.map((h) => [h.date, h.name]),
    );

    await insertBatch(
      client,
      "time_off",
      ["id", "user_id", "date", "label"],
      seed.timeOff.map((t) => [t.id, t.userId, t.date, t.label]),
    );

    await insertBatch(
      client,
      "timesheets",
      ["id", "user_id", "entity_id", "week_ending", "stream_id", "customer_id", "notes"],
      seed.timesheets.map((t) => [t.id, t.userId, t.entityId, t.weekEnding, t.streamId, t.customerId, t.notes]),
    );

    await insertBatch(
      client,
      "events",
      ["id", "timesheet_id", "type", "actor_id", "at", "payload"],
      seed.events.map((e) => [e.id, e.timesheetId, e.type, e.actorId, e.at, JSON.stringify(e.payload)]),
    );

    await insertBatch(
      client,
      "notifications",
      ["id", "user_id", "at", "read_at", "text", "target"],
      seed.notifications.map((n) => [n.id, n.userId, n.at, n.readAt, n.text, JSON.stringify(n.target)]),
    );

    await insertBatch(
      client,
      "chases",
      ["id", "at", "by_user_id", "target_user_id"],
      seed.chases.map((c) => [c.id, c.at, c.byUserId, c.targetUserId]),
    );

    await insertBatch(
      client,
      "admin_log",
      ["id", "at", "actor_id", "user_id", "text"],
      seed.adminLog.map((a) => [a.id, a.at, a.actorId, a.userId, a.text]),
    );

    // Every row above was inserted with an explicit id, so each identity
    // sequence is still at its start value — bump it past the max id we
    // used, or the next ordinary (id-omitting) insert would collide.
    for (const table of IDENTITY_TABLES) {
      await client.query(
        `select setval(pg_get_serial_sequence($1, 'id'), coalesce((select max(id) from ${table}), 1), true)`,
        [table],
      );
    }

    await client.query("commit");
  } catch (err) {
    await client.query("rollback");
    throw err;
  }
}

const TABLES = [
  "entities", "users", "rates", "customers", "streams", "accounts",
  "holidays", "time_off", "timesheets", "events", "notifications",
  "chases", "admin_log",
];

async function printRowCounts(client: PoolClient) {
  console.log("\nRows per table:");
  for (const table of TABLES) {
    const result = await client.query<{ count: string }>(`select count(*) from ${table}`);
    console.log(`  ${table.padEnd(14)} ${result.rows[0].count}`);
  }
}

async function runVerifications(client: PoolClient) {
  console.log("\nVerification queries (each must be 0):");

  const checks: { name: string; sql: string }[] = [
    {
      name: "timesheets with hours on a blocked day",
      sql: `
        with submitted as (
          select e.timesheet_id, t.user_id, t.week_ending, e.payload
          from events e join timesheets t on t.id = e.timesheet_id
          where e.type = 'submitted'
        )
        select count(*) from submitted d
        cross join lateral (values
          ((d.week_ending - interval '4 day')::date, (d.payload->'hours'->>'mon')::numeric),
          ((d.week_ending - interval '3 day')::date, (d.payload->'hours'->>'tue')::numeric),
          ((d.week_ending - interval '2 day')::date, (d.payload->'hours'->>'wed')::numeric),
          ((d.week_ending - interval '1 day')::date, (d.payload->'hours'->>'thu')::numeric),
          (d.week_ending::date, (d.payload->'hours'->>'fri')::numeric)
        ) as day_hours(day_date, hours)
        where hours > 0
          and (
            exists (select 1 from holidays h where h.date = day_hours.day_date)
            or exists (select 1 from time_off tof where tof.user_id = d.user_id and tof.date = day_hours.day_date)
          )
      `,
    },
    {
      name: "submissions exceeding their own snapshotted caps",
      sql: `
        select count(*) from events e
        where e.type = 'submitted'
          and (
            (e.payload->>'totalHours')::numeric > (e.payload->>'weeklyCap')::numeric
            or exists (
              select 1 from jsonb_each_text(e.payload->'hours') h(day, val)
              where val::numeric > (e.payload->>'dailyCap')::numeric
            )
          )
      `,
    },
    {
      name: "timesheets whose events are out of chronological order",
      sql: `
        select count(*) from (
          select id, timesheet_id, at,
                 lag(at) over (partition by timesheet_id order by id) as prev_at
          from events
        ) x
        where prev_at is not null and at <= prev_at
      `,
    },
    {
      name: "approved events whose rate differs from the rate in force for that week ending",
      sql: `
        select count(*) from events e
        join timesheets t on t.id = e.timesheet_id
        where e.type = 'approved'
          and (e.payload->>'hourly')::numeric <> (
            select r.hourly from rates r
            where r.user_id = t.user_id and r.effective_from <= t.week_ending
            order by r.effective_from desc limit 1
          )
      `,
    },
    {
      name: "timesheets whose user's entity differs from the timesheet's entity",
      sql: `
        select count(*) from timesheets t
        join users u on u.id = t.user_id
        where u.entity_id <> t.entity_id
      `,
    },
    {
      name: "processed events whose account differs from the resolution rule",
      sql: `
        select count(*) from events e
        join timesheets t on t.id = e.timesheet_id
        join streams s on s.id = t.stream_id
        join users u on u.id = t.user_id
        where e.type = 'processed'
          and (e.payload->>'expenseAccount') is distinct from (
            case
              when s.billable then s.default_account
              else (
                case u.function
                  when 'Delivery' then '5000'
                  when 'Solutions & Support' then '5020'
                  when 'Product Engineering' then '6100'
                  when 'R&D' then '6100'
                  when 'Sales & Marketing' then '6000'
                  when 'G&A' then '6200'
                end
              )
            end
          )
      `,
    },
    {
      name: "timesheets whose customer belongs to a different entity than the timesheet",
      sql: `
        select count(*) from timesheets t
        join customers c on c.id = t.customer_id
        where t.customer_id is not null and c.entity_id <> t.entity_id
      `,
    },
  ];

  for (const check of checks) {
    const result = await client.query<{ count: string }>(check.sql);
    const count = result.rows[0].count;
    console.log(`  [${count === "0" ? "PASS" : "FAIL"}] ${check.name}: ${count}`);
  }
}

// Unlike the checks above, this one must be NON-zero: every status the app
// can show should actually have at least one timesheet in it, or a queue
// screen would look broken on arrival. Uses the same lib/status.ts mapping
// every screen uses — not a separate SQL re-implementation of it.
async function runStatusCoverageCheck(client: PoolClient) {
  console.log("\nStatus coverage (must be non-zero):");

  const result = await client.query<{ type: string }>(`
    select latest.type
    from (
      select distinct on (timesheet_id) timesheet_id, type
      from events
      order by timesheet_id, at desc, id desc
    ) latest
  `);
  const counts = Object.fromEntries(STATUSES.map((s) => [s, 0])) as Record<(typeof STATUSES)[number], number>;
  for (const row of result.rows) {
    counts[statusFromLatestEventType(row.type)]++;
  }

  const allNonZero = STATUSES.every((s) => counts[s] > 0);
  const breakdown = STATUSES.map((s) => `${s}=${counts[s]}`).join(", ");
  console.log(
    `  [${allNonZero ? "PASS" : "FAIL"}] each of draft, submitted, approved and processed has at least one timesheet: ${breakdown}`,
  );
}

async function proveAppendOnly(client: PoolClient) {
  console.log("\nAppend-only trigger proof (events table):");

  try {
    await client.query("update events set type = 'reopened' where id = (select min(id) from events)");
    console.log("  UPDATE: did not raise — THIS IS A BUG");
  } catch (err) {
    console.log(`  UPDATE raised: ${(err as Error).message}`);
  }

  try {
    await client.query("delete from events where id = (select min(id) from events)");
    console.log("  DELETE: did not raise — THIS IS A BUG");
  } catch (err) {
    console.log(`  DELETE raised: ${(err as Error).message}`);
  }
}

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  const seed = buildSeed(new Date());

  if (dryRun) {
    console.log(summarize(seed));
    return;
  }

  const connectionString = process.env.DIRECT_URL ?? process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error("DIRECT_URL or DATABASE_URL must be set");
  }

  const pool = new Pool({ connectionString });
  const client = await pool.connect();
  try {
    console.log("Seeding database...");
    await seedDatabase(client, seed);
    console.log("Seed committed.");
    console.log(summarize(seed));
    await printRowCounts(client);
    await runVerifications(client);
    await runStatusCoverageCheck(client);
    await proveAppendOnly(client);
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch((err) => {
  console.error("Seed failed:", err.message ?? err);
  process.exit(1);
});
